#!/usr/bin/env bash
# 1コードベースから複数の GCP プロジェクト(テナント)へ撃ち分けるデプロイスクリプト。
#
#   ./deploy/deploy.sh <tenant> [target] [flags]
#
#   <tenant>  deploy/tenants/<tenant>.env のテナント名 (例: forpeple, marketing)
#   [target]  hosting | firestore | backend | all   (省略時 all)
#   flags:
#     --dry-run   生成内容と実行予定コマンドを表示するだけで deploy しない
#     --yes       確認プロンプトをスキップ
#
# テナント差はすべて tenants/<tenant>.env に集約。新テナントは .env を1つ足すだけ。
set -euo pipefail

# --- パス解決 (どこから呼んでもリポジトリルート基準で動く) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TENANT_DIR="$SCRIPT_DIR/tenants"

# --- 引数パース ---
TENANT=""
TARGET="all"
DRY_RUN=0
ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --yes|-y)  ASSUME_YES=1 ;;
    hosting|firestore|backend|all) TARGET="$arg" ;;
    -*) echo "ERROR: 不明なフラグ: $arg" >&2; exit 2 ;;
    *)
      if [ -z "$TENANT" ]; then TENANT="$arg"
      else echo "ERROR: 引数が多すぎます: $arg" >&2; exit 2; fi
      ;;
  esac
done

if [ -z "$TENANT" ]; then
  echo "使い方: ./deploy/deploy.sh <tenant> [hosting|firestore|backend|all] [--dry-run] [--yes]" >&2
  echo "登録テナント:" >&2
  for f in "$TENANT_DIR"/*.env; do
    [ -e "$f" ] || continue
    b="$(basename "$f" .env)"
    [ "$b" = "_example" ] && continue
    echo "  - $b" >&2
  done
  exit 2
fi

ENV_FILE="$TENANT_DIR/$TENANT.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: テナント定義が見つかりません: $ENV_FILE" >&2
  echo "       deploy/tenants/_example.env をコピーして作成してください。" >&2
  exit 1
fi

# --- テナント定義の読み込み ---
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# --- 必須変数の検証 ---
REQUIRED=(PROJECT_ID PROJECT_NUMBER REGION API_KEY APP_ID)
MISSING=()
for v in "${REQUIRED[@]}"; do
  if [ -z "${!v:-}" ]; then MISSING+=("$v"); fi
done
if [ "${#MISSING[@]}" -gt 0 ]; then
  echo "ERROR: $ENV_FILE に必須変数が未設定です: ${MISSING[*]}" >&2
  exit 1
fi
# backend を実デプロイするなら OAuth client id も必須（dry-run では警告のみ）
if { [ "$TARGET" = "backend" ] || [ "$TARGET" = "all" ]; } && [ -z "${GOOGLE_OAUTH_CLIENT_ID:-}" ]; then
  msg_oauth_get="既存 Cloud Run から取得: gcloud run services describe dashboard-backend --project $PROJECT_ID --region ${REGION:-asia-northeast1} --format='value(spec.template.spec.containers[0].env)'"
  if [ "$DRY_RUN" = "1" ]; then
    echo "WARN: GOOGLE_OAUTH_CLIENT_ID 未設定（dry-run のため続行）。実 backend デプロイ前に $ENV_FILE へ記入してください。" >&2
    echo "      $msg_oauth_get" >&2
  else
    echo "ERROR: backend デプロイには GOOGLE_OAUTH_CLIENT_ID が必要です ($ENV_FILE に記入してください)。" >&2
    echo "       $msg_oauth_get" >&2
    exit 1
  fi
fi

USE_BACKEND_AGGREGATE="${USE_BACKEND_AGGREGATE:-true}"

# --- 確認プロンプト ---
echo "============================================================"
echo " テナント   : $TENANT"
echo " プロジェクト: $PROJECT_ID  (番号: $PROJECT_NUMBER)"
echo " リージョン : $REGION"
echo " ターゲット : $TARGET"
[ "$DRY_RUN" = "1" ] && echo " モード     : DRY-RUN (deploy しません)"
echo "============================================================"
if [ "$ASSUME_YES" != "1" ] && [ "$DRY_RUN" != "1" ]; then
  read -r -p "このプロジェクトへデプロイします。よろしいですか? (yes/no) " ans
  if [ "$ans" != "yes" ]; then echo "中止しました。"; exit 0; fi
fi

# --- 生成: app-config.js ---
APP_CONFIG_PATH="$ROOT_DIR/app-config.js"
gen_app_config() {
  {
    echo "// AUTO-GENERATED by deploy/deploy.sh for $PROJECT_ID (${APP_NAME:-$PROJECT_ID})"
    echo "// 手で編集しない / コミットしない (gitignore)。値は deploy/tenants/$TENANT.env を編集する。"
    echo "window.__APP_CONFIG__ = {"
    echo "  firebase: {"
    echo "    apiKey: '$API_KEY',"
    echo "    authDomain: '$PROJECT_ID.firebaseapp.com',"
    echo "    projectId: '$PROJECT_ID',"
    echo "    appId: '$APP_ID',"
    echo "  },"
    echo "  apiBase: '',"
    if [ -n "${APP_CHECK_SITE_KEY:-}" ]; then
      echo "  appCheckSiteKey: '$APP_CHECK_SITE_KEY',"
    fi
    echo "  features: {"
    echo "    useBackendAggregate: $USE_BACKEND_AGGREGATE,"
    echo "  },"
    echo "};"
  }
}

# --- 生成: .firebaserc ---
FIREBASERC_PATH="$ROOT_DIR/.firebaserc"
gen_firebaserc() {
  printf '{\n  "projects": {\n    "default": "%s"\n  }\n}\n' "$PROJECT_ID"
}

if [ "$DRY_RUN" = "1" ]; then
  echo; echo "----- 生成される app-config.js -----"; gen_app_config
  echo; echo "----- 生成される .firebaserc -----"; gen_firebaserc
else
  gen_app_config > "$APP_CONFIG_PATH"
  gen_firebaserc > "$FIREBASERC_PATH"
  echo "✓ app-config.js / .firebaserc を $PROJECT_ID 向けに生成しました。"
fi

# --- 実行ヘルパ (dry-run ならコマンドを表示するだけ) ---
run() {
  echo "+ $*"
  if [ "$DRY_RUN" != "1" ]; then "$@"; fi
}

do_firestore() {
  echo; echo "### firestore rules/indexes -> $PROJECT_ID"
  run firebase deploy --only firestore:rules,firestore:indexes --project "$PROJECT_ID"
}
do_hosting() {
  echo; echo "### hosting -> $PROJECT_ID"
  run firebase deploy --only hosting --project "$PROJECT_ID"
}
do_backend() {
  echo; echo "### backend (Cloud Run dashboard-backend) -> $PROJECT_ID"
  # --update-env-vars を使う（--set-env-vars は総入れ替えで、別途設定済みの
  # CLOUD_RUN_URL / SCHEDULER_SA_EMAIL 等を消してしまうため）。指定キーのみ更新し他は保持。
  local env_vars
  env_vars="GCP_PROJECT_ID=$PROJECT_ID,SNAPSHOT_BUCKET=$PROJECT_ID-snapshots,GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID,OAUTH_REDIRECT_URI=https://dashboard-backend-$PROJECT_NUMBER.$REGION.run.app/api/google/auth/callback,NODE_ENV=production"
  ( cd "$ROOT_DIR/backend" && run gcloud run deploy dashboard-backend \
      --source . \
      --region "$REGION" \
      --project "$PROJECT_ID" \
      --allow-unauthenticated \
      --service-account "dashboard-backend@$PROJECT_ID.iam.gserviceaccount.com" \
      --update-env-vars "$env_vars" )
}

case "$TARGET" in
  firestore) do_firestore ;;
  hosting)   do_hosting ;;
  backend)   do_backend ;;
  all)       do_firestore; do_hosting; do_backend ;;
esac

echo
if [ "$DRY_RUN" = "1" ]; then
  echo "DRY-RUN 完了 (何もデプロイしていません)。"
else
  echo "✓ デプロイ完了: $TENANT ($PROJECT_ID) / target=$TARGET"
  echo "  確認: https://$PROJECT_ID.web.app"
fi
